# Generated by Django 4.1 on 2022-08-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.CharField(max_length=255, null=True)),
                ('character', models.CharField(max_length=255, null=True)),
                ('quote', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
